deploy/app/report/forms.py
#coding:utf-8
from flask_babelex import lazy_gettext as _
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired
from wtforms import SubmitField, TextAreaField, SelectField, HiddenField
from wtforms.fields.html5 import DateField


class WriteForm(FlaskForm):
    body = TextAreaField(_("This week's work content and plan of next week"),
                         validators=[DataRequired()])
    last_content = HiddenField(_("This week's work content and plan of last week"))                         
    submit = SubmitField(_('Submit'))


class ReadDepartmentForm(FlaskForm):
    user = SelectField(_('Username'))
    start_at = DateField(_('Start'), format='%Y-%m-%d')
    end_at = DateField(_('End'), format='%Y-%m-%d')
    submit = SubmitField(_('Query'))


class ReadCrewForm(ReadDepartmentForm):
    department = SelectField(_('Department'))


class EmailReminderForm(FlaskForm):
    submit = SubmitField(_('Send Reminder Email'))

deploy/app/report/__init__.py
from flask import Blueprint

report = Blueprint('report', __name__)

from . import views

deploy/app/report/views.py
#coding:utf-8
from flask import render_template, redirect,request, url_for, \
    current_app, flash, Markup
from flask_babelex import lazy_gettext as _
from flask_login import current_user
from datetime import datetime, timedelta, date
from . import report
from .forms import WriteForm, ReadDepartmentForm, \
    ReadCrewForm, EmailReminderForm
from .. import db
from ..email import send_email
from ..models import Permission, User, Report, Department
from ..utils import get_week_count, permission_required, get_this_monday, \
    get_last_week, get_last_week_start_at, get_last_week_end_at, get_last_week_content


@report.route('/write/', methods=['GET', 'POST'])
@permission_required(Permission.WRITE_REPORT)
def write():
    form = WriteForm()
    last_content_display = ""
    report = Report.query.filter_by(
        author_id=current_user.id,
        week_count=get_week_count(),
        year=datetime.today().year
    ).first()
    
    last_report = Report.query.filter_by(
        author_id=current_user.id,
        week_count=get_week_count() - 1,
        year=datetime.today().year
    ).first()
    
    if form.submit.data and form.validate_on_submit():
        if report:
            report.content = form.body.data.replace('<br>', '')
            # report.content = form.bodycontent.data.replace('<br>', '')
            report.last_content = form.last_content.data.replace('<br>', '')
            db.session.add(report)
        else:
            report = Report(
                content=form.body.data.replace('<br>', ''),
                # content=form.bodycontent.data.replace('<br>', ''),
                last_content=form.last_content.data.replace('<br>', ''),
                author_id=current_user.id,
                week_count=get_week_count(),
                year=datetime.today().year)
            db.session.add(report)
        db.session.commit()
        flash(_('Successfully submitted report'))

        current_app.logger.info(
            '{} submitted report'.format(current_user.email))

        return redirect(url_for('report.write'))

    if report:
        form.body.data = report.content
        # form.bodycontent.data = report.content
    else:
        form.body.data = current_app.config['DEFAULT_CONTENT']
        # form.bodycontent.data = current_app.config['DEFAULT_CONTENT']
    if last_report:
        form.last_content.data = last_report.content
        last_content_display = get_last_week_content(last_report.content)

    return render_template('report/write.html',
                           form=form,
                           week_count=get_week_count(),
                           start_at=get_this_monday(),
                           end_at=get_this_monday()+timedelta(days=6),
                           last_content_display=last_content_display)


@report.route('/write/last_week', methods=['GET', 'POST'])
@permission_required(Permission.WRITE_REPORT)
def write_last_week():
    form = WriteForm()
    last_content_display = ""
    
    report = Report.query.filter_by(
        author_id=current_user.id,
        week_count=get_week_count(get_last_week()),
        year=get_last_week().year).first()
        
    last_report = Report.query.filter_by(
        author_id=current_user.id,
        week_count=get_week_count(get_last_week()) - 1,
        year=get_last_week().year).first()

    if form.submit.data and form.validate_on_submit():
        if report:
            report.content = form.body.data.replace('<br>', '')
            # report.content = form.bodycontent.data.replace('<br>', '')
            report.last_content = form.last_content.data.replace('<br>', '')
        else:
            report = Report(
                content=form.body.data.replace('<br>', ''),
                # content=form.bodycontent.data.replace('<br>', ''),
                author_id=current_user.id,
                week_count=get_week_count(get_last_week()),
                year=get_last_week().year)
        db.session.add(report)
        db.session.commit()
        flash(_('Successfully submitted report'))

        current_app.logger.info(
            "{} edited last week's report".format(current_user.email))

        return redirect(url_for('report.write_last_week'))

    if report:
        form.body.data = report.content
        # form.bodycontent.data = report.content
    else:
        form.body.data = current_app.config['DEFAULT_CONTENT']
        # form.bodycontent.data = current_app.config['DEFAULT_CONTENT']
        
    if last_report:
        form.last_content.data = last_report.content
        last_content_display = get_last_week_content(last_report.content)
                
    return render_template('report/write.html',
                           form=form,
                           week_count=get_week_count(get_last_week()),
                           start_at=get_last_week_start_at(),
                           end_at=get_last_week_end_at() - timedelta(days=1),
                           last_content_display=last_content_display)


@report.route('/read/', methods=['GET'])
@report.route('/read/<int:page_count>', methods=['GET'])
@permission_required(Permission.WRITE_REPORT)
def read(page_count=1):
    if not Report.query.filter_by(
            author_id=current_user.id,
            week_count=get_week_count(get_last_week()),
            year=get_last_week().year).first():
        flash(Markup(_("Do you want to <a href='/report/write/last_week'>"
                       "edit last week's report?</a>")))

    pagination = Report.query.filter_by(author_id=current_user.id).order_by(
        Report.year.desc()).order_by(Report.week_count.desc()).paginate(
        page=page_count, per_page=current_app.config['PER_PAGE'])
    if not Report.query.filter_by(
            author_id=current_user.id,
            week_count=get_week_count(),
            year=datetime.today().year):
        flash(_("You haven't submitted your weekly report"))
    return render_template('report/read.html', pagination=pagination)


@report.route('/read/department/', methods=['GET', 'POST'])
@permission_required(Permission.READ_DEPARTMENT_REPORT)
def read_department():
    form = ReadDepartmentForm()

    user_choices = [('0', '*')]
    user_choices.extend([(
        str(user.id), user.username) for user in User.query.all()])
    form.user.choices = user_choices

    page = request.args.get('page', 1, type=int)
    user_id = request.args.get('user', 0, type=int)
    start_at = request.args.get('start_at', '', type=str)
    end_at = request.args.get('end_at', '', type=str)

    start_at = get_last_week_start_at() if not start_at \
        else datetime.strptime(start_at[:10], '%Y-%m-%d')
    end_at = date.today()+timedelta(hours=24) if not end_at \
        else datetime.strptime(end_at[:10], '%Y-%m-%d')

    form.start_at.data = start_at
    form.end_at.data = end_at
    form.user.data = str(user_id)

    ids = [user.id for user in User.query.filter_by(
        department_id=current_user.department_id)]

    qst = Report.query.filter_by().filter(
        Report.created_at.between(start_at, end_at)).filter(
        Report.author_id.in_(ids))

    if user_id:
        qst = qst.filter_by(author_id=user_id)

    if form.validate_on_submit():
        pass

    pagination = qst.filter_by().order_by(Report.year.desc()).order_by(
        Report.week_count.desc()).order_by(Report.created_at.desc()).paginate(
            page=page, per_page=current_app.config['PER_PAGE'])

    return render_template('report/read_department.html',
                           form=form,
                           pagination=pagination)


@report.route('/read/crew/', methods=['GET', 'POST'])
@permission_required(Permission.READ_ALL_REPORT)
def read_crew():
    form = ReadCrewForm()
    user_choices = [('0', '*')]
    department_choices = user_choices[:]

    for dept in Department.query.all():
        department_choices.extend([(str(dept.id), dept.name)])
        user_choices.extend([(str(user.id), user.username) for user in
                             User.query.filter_by(department_id=dept.id)])

    form.user.choices = user_choices
    form.department.choices = department_choices

    page = request.args.get('page', 1, type=int)
    department_id = request.args.get('department', 0, type=int)
    user_id = request.args.get('user', 0, type=int)
    start_at = request.args.get('start_at', '', type=str)
    end_at = request.args.get('end_at', '', type=str)

    start_at = get_last_week_start_at() if not start_at \
        else datetime.strptime(start_at[:10], '%Y-%m-%d')
    end_at = date.today()+timedelta(hours=24) if not end_at \
        else datetime.strptime(end_at[:10], '%Y-%m-%d')

    form.start_at.data = start_at
    form.end_at.data = end_at
    form.user.data = str(user_id)
    form.department.data = str(department_id)

    qst = Report.query.filter_by().filter(
        Report.created_at.between(start_at, end_at))

    if department_id:
        ids = [user.id for user in User.query.filter_by(
            department_id=department_id)]
        qst = qst.filter(Report.author_id.in_(ids))

    if user_id:
        qst = qst.filter_by(author_id=user_id)

    if form.validate_on_submit():
        pass

    pagination = qst.filter_by().order_by(Report.year.desc()).order_by(
        Report.week_count.desc()).order_by(Report.created_at.desc()).paginate(
            page=page, per_page=current_app.config['PER_PAGE'])

    return render_template('report/read_crew.html',
                           form=form,
                           pagination=pagination)


@report.route('/statistics/department/', methods=['GET'])
@permission_required(Permission.READ_DEPARTMENT_REPORT)
def statistics_department():
    qst = Report.query.filter_by()
    dept_users = [user for user in User.query.filter_by(
        department_id=current_user.department_id) if not user.is_ignored]
    ids = [user.id for user in dept_users]
    if ids:
        qst = qst.filter(Report.author_id.in_(ids))
    else:

deploy/app/templates/report/read.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block page_content %}



    {% for report in pagination.items %}
    <div class="post-preview">


        <a rel="tag" class="post-tag">{{_('Employee')}}:{{ report.author.username }}</a>
        <a rel="tag" class="post-tag">{{_('Department')}}:{{ report.department.name }}</a>
        <a rel="tag" class="post-tag">{{_('Week Count')}}:{{ report.week_count }}</a>
        <a rel="tag" class="post-tag">{{_('Year')}}:{{ report.year }}</a>
		<a rel="tag" class="post-tag">{{_('Start')}}:{{ report.year | get_week_days(report.week_count,0) }}</a>
		<a rel="tag" class="post-tag">{{_('End')}}:{{ report.year | get_week_days(report.week_count,1) }}</a>
        
        {{report.content|safe}}

        {% if report.is_of_current_week %}
            <a href="{{url_for('report.write')}}" rel="tag" class="post-edit-tag">{{_('Edit')}}</a>
        {% endif %}

        {% if report.is_of_last_week %}
            <a href="{{url_for('report.write_last_week')}}" rel="tag" class="post-edit-tag">{{_('Edit')}}</a>
        {% endif %}

        <div><hr></div>
    </div>
    {% endfor %}

    <ul class="pager">
        {% if pagination.has_prev %}
            <li class="previous"><a href="/my_report/{{pagination.page-1 }}">&larr; Newer </a></li>
        {% else %}
            <li class="previous disabled"><a href="#">&larr; Newer </a></li>
        {% endif %}

        {% if pagination.has_next %}
            <li class="next"><a href="/my_report/{{pagination.page+1}}">Older &rarr;</a></li>
        {% else %}
            <li class="next disabled"><a href="#">Older &rarr;</a></li>
        {% endif %}
    </ul>

{% endblock %}

{% block script %}

<script type="text/javascript" src="{{ url_for('static', filename='katex-element/dist/katex-element.umd.js')}}"></script>

<script>
    function replaceKaTex(){
        var isspan = document.querySelectorAll('span')
        var num = isspan.length
        if (num > 0 ){
            for (i=0;i<num;i++){
                if(isspan[i].getAttribute('data-value') != null){
                    isspan[i].innerHTML = "<katex-element>"+isspan[i].getAttribute('data-value')+"</katex-element>"
                }
            }
        }
    };
    replaceKaTex();
</script>

{% endblock %}

deploy/app/templates/report/read_crew.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block page_content %}

    <form class="form form-inline" method="GET" role="form">
        {{ wtf.form_errors(form, hiddens="only") }}

        <i class="fa fa-calendar-minus-o" aria-hidden="true"></i>{{ wtf.form_field(form.start_at) }}
        <i class="fa fa-calendar-plus-o" aria-hidden="true"></i>{{ wtf.form_field(form.end_at) }}
        <hr style="height:10pt; visibility:hidden;" />

        <i class="fa fa-user" aria-hidden="true"></i>{{ wtf.form_field(form.user) }}
        <i class="fa fa-users" aria-hidden="true"></i>{{ wtf.form_field(form.department) }}

        <i class="fa fa-search" aria-hidden="true"></i>{{ wtf.form_field(form.submit) }}
    </form>
    <hr>


    {% for report in pagination.items %}
    <div class="post-preview">

        <a rel="tag" class="post-tag">{{_('Employee')}}:{{ report.author.username }}</a>
        <a rel="tag" class="post-tag">{{_('Department')}}:{{ report.department.name }}</a>
        <a rel="tag" class="post-tag">{{_('Week Count')}}:{{ report.week_count }}</a>
        <a rel="tag" class="post-tag">{{_('Year')}}:{{ report.year }}</a>
		<a rel="tag" class="post-tag">{{_('Start')}}:{{ report.year | get_week_days(report.week_count,0) }}</a>
		<a rel="tag" class="post-tag">{{_('End')}}:{{ report.year | get_week_days(report.week_count,1) }}</a>		
        <table class="table table-striped table-bordered table-hover model-list">
        <thead>
            <tr>
	              <th class="column-header col-last_content">
	                  {{_('Last Week')}}
	              </th>
	              
	              <th class="column-header col-content">
	                  {{_('Current Week')}}
	              </th>
            </tr>
        </thead>
        <tbody><tr>
                    <td class="col-last_content">
                            {{report.last_content|safe}}
                    </td>
                
                    <td class="col-content">
                            {{report.content|safe}}
                    </td>
            
        </tr>
        </tbody>
					</table>
        
        <hr>
    </div>
    {% endfor %}

    <ul class="pager">
        {% if pagination.has_prev %}
            <li class="previous">
                <a href="{{ url_for('report.read_crew',
                page=pagination.page-1,
                start_at=form.start_at.data,
                end_at=form.end_at.data,
                user=form.user.data,
                department=form.department.data
                )}}">
                    &larr; Newer
                </a>
            </li>
        {% else %}
            <li class="previous disabled"><a href="#">&larr; Newer </a></li>
        {% endif %}

        {% if pagination.has_next %}
            <li class="next">
                <a href="{{ url_for('report.read_crew',
                page=pagination.page+1,
                start_at=form.start_at.data,
                end_at=form.end_at.data,
                user=form.user.data,
                department=form.department.data
                )}}">
                    Older &rarr;
                </a>
            </li>
        {% else %}
            <li class="next disabled"><a href="#">Older &rarr;</a></li>
        {% endif %}
    </ul>

{% endblock %}

{% block script %}
<script type="text/javascript" src="{{ url_for('static', filename='katex-element/dist/katex-element.umd.js')}}"></script>

<script>
    function replaceKaTex(){
        var isspan = document.querySelectorAll('span')
        var num = isspan.length
        if (num > 0 ){
            for (i=0;i<num;i++){
                if(isspan[i].getAttribute('data-value') != null){
                    isspan[i].innerHTML = "<katex-element>"+isspan[i].getAttribute('data-value')+"</katex-element>"
                }
            }
        }
    };
    replaceKaTex();
</script>

{% endblock %}

deploy/app/templates/report/read_department.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block page_content %}

    <form class="form form-inline" method="GET" role="form">
        {{ wtf.form_errors(form, hiddens="only") }}

        <i class="fa fa-calendar-minus-o" aria-hidden="true"></i>{{ wtf.form_field(form.start_at) }}
        <i class="fa fa-calendar-plus-o" aria-hidden="true"></i>{{ wtf.form_field(form.end_at) }}

        <i class="fa fa-user" aria-hidden="true"></i>{{ wtf.form_field(form.user) }}
        <i class="fa fa-search" aria-hidden="true"></i>{{ wtf.form_field(form.submit) }}
    </form>
    <hr>

    {% for report in pagination.items %}
    <div class="post-preview">

        <a rel="tag" class="post-tag">{{_('Employee')}}:{{ report.author.username }}</a>
        <a rel="tag" class="post-tag">{{_('Department')}}:{{ report.department.name }}</a>
        <a rel="tag" class="post-tag">{{_('Week Count')}}:{{ report.week_count }}</a>
        <a rel="tag" class="post-tag">{{_('Year')}}:{{ report.year }}</a>

        {{report.content|safe}}
        <hr>
    </div>
    {% endfor %}

    <ul class="pager">
        {% if pagination.has_prev %}
            <li class="previous">
                <a href="{{ url_for('report.read_department',
                page=pagination.page-1,
                start_at=form.start_at.data,
                end_at=form.end_at.data,
                user=form.user.data,
                )}}">
                    &larr; Newer
                </a>
            </li>
        {% else %}
            <li class="previous disabled"><a href="#">&larr; Newer </a></li>
        {% endif %}

        {% if pagination.has_next %}
            <li class="next">
                <a href="{{ url_for('report.read_department',
                page=pagination.page+1,
                start_at=form.start_at.data,
                end_at=form.end_at.data,
                user=form.user.data,
                )}}">
                    Older &rarr;
                </a>
            </li>        {% else %}
            <li class="next disabled"><a href="#">Older &rarr;</a></li>
        {% endif %}
    </ul>

{% endblock %}

{% block script %}
<script type="text/javascript" src="{{ url_for('static', filename='katex-element/dist/katex-element.umd.js')}}"></script>

<script>
    function replaceKaTex(){
        var isspan = document.querySelectorAll('span')
        var num = isspan.length
        if (num > 0 ){
            for (i=0;i<num;i++){
                if(isspan[i].getAttribute('data-value') != null){
                    isspan[i].innerHTML = "<katex-element>"+isspan[i].getAttribute('data-value')+"</katex-element>"
                }
            }
        }
    };
    replaceKaTex();
</script>

{% endblock %}

deploy/app/templates/report/statistics_crew.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block head_script %}
    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" /> -->
    <!-- <script src="{{ url_for('static', filename='js/moment.min.js')}}"></script>
    <script>
        window.moment = require('moment');
    </script> -->
    <script src="{{ url_for('static', filename='chartkick/Chart.bundle.min.js') }}"></script>
    <script src="{{ url_for('static', filename='chartkick/chartkick.js') }}"></script>
{% endblock %}


{% block page_content %}
<div class="post-preview">

    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-bar-chart aria-hidden=true"></i>
            第{{ week_count }}周 ({{start_at}}至{{end_at}}) 各部门未交周报人数统计
            {% if get_this_week_count() == week_count %}
                <a href="{{url_for('report.statistics_crew_last_week')}}">
                    (查看上周)
                </a>
            {% endif %}
        </div>
        <div class="panel-body">
            {% for key, value in contrast.items() %}
            <a>{{ key }}:</a>{{value}}
            <br/>
            {% endfor %}
        </div>
    </div>


    {% for dept in stash %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-users" aria-hidden="true"></i>
                {{ dept.dept_name }}
            </div>

            <div class="panel-body">

                <a>已交:</a>
                    {% for name in dept['names']['has_submitted'] %}
                        <a rel="tag" class="post-tag">{{ name }}</a>
                    {% endfor %}

                <hr style="height:2pt; visibility:hidden;" />

                <a>未交:</a>
                    {% for name in dept['names']['not_yet'] %}
                        <a rel="tag" class="post-red-tag">{{ name }}</a>
                    {% endfor %}
                <br>
            </div>

        </div>
    {% endfor %}

</div>

{#
{{ wtf.quick_form(form) }}
#}

{% endblock %}

deploy/app/templates/report/statistics_department.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block head_script %}
    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" /> -->
    <!-- <script src="{{ url_for('static', filename='js/moment.min.js')}}"></script>
    <script>
        window.moment = require('moment');
    </script> -->
    <script src="{{ url_for('static', filename='chartkick/Chart.bundle.min.js') }}"></script>
    <script src="{{ url_for('static', filename='chartkick/chartkick.js') }}"></script>
{% endblock %}


{% block page_content %}
<div class="post-preview">


    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-pie-chart" aria-hidden="true"></i>
            第{{ week_count }}周 ({{start_at}}至{{end_at}}) {{current_user.department.name}} 周报统计
            {% if get_this_week_count() == week_count %}
                <a href="{{url_for('report.statistics_department_last_week')}}">
                    (查看上周)
                </a>
            {% endif %}
        </div>
        <div class="panel-body">
        {% pie_chart data %}
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-users" aria-hidden="true"></i>
            {{ current_user.department.name }}
        </div>

        <div class="panel-body">

            <a>已交:</a>
                {% for name in names['has_submitted'] %}
                    <a rel="tag" class="post-tag">{{ name }}</a>
                {% endfor %}
            <hr style="height:2pt; visibility:hidden;" />
            <a>未交:</a>
                {% for name in names['not_yet'] %}
                    <a rel="tag" class="post-red-tag">{{ name }}</a>
                {% endfor %}
        </div>
    </div>
</div>
{% endblock %}